theme: jekyll-theme-minimal
title: Cardboard
description: Super extra high performance Paper fork that aims to make Minecraft huge way way a lot much less laggier.
logo: https://tehbrian.xyz/resources/smallcardboard.png
